import React,{useMemo,useRef,useState} from 'react'
import {PDFDocument} from 'pdf-lib'
import PdfViewer from './viewers/PdfViewer.jsx'
import ImageViewer from './viewers/ImageViewer.jsx'
import DocxViewer from './viewers/DocxViewer.jsx'
import XlsxViewer from './viewers/XlsxViewer.jsx'
import HwpViewer from './viewers/HwpViewer.jsx'
import PptxViewer from './viewers/PptxViewer.jsx'
const SUPPORTED=['pdf','jpg','jpeg','png','hwp','hwpx','docx','xlsx','pptx'];const MERGEABLE=new Set(['pdf','jpg','jpeg','png']);
const ext=(n='')=>n.split('.').pop()?.toLowerCase()||'';const fileLabel=t=>['jpg','jpeg','png'].includes(t)?'이미지':t.toUpperCase();const prettySize=b=>b<1024?`${b} B`:b<1048576?`${(b/1024).toFixed(1)} KB`:`${(b/1048576).toFixed(1)} MB`;const uid=()=>`${Date.now()}_${Math.random().toString(36).slice(2)}`;
function Viewer({item,onClose}){const t=ext(item.file.name);return <div className="viewer-overlay"><div className="viewer-header"><button className="back-btn" onClick={onClose}>← 목록</button><div><strong>{item.file.name}</strong><small>{fileLabel(t)} · {prettySize(item.file.size)}</small></div></div><div className="viewer-body">{t==='pdf'&&<PdfViewer file={item.file}/>} {['jpg','jpeg','png'].includes(t)&&<ImageViewer file={item.file}/>} {t==='docx'&&<DocxViewer file={item.file}/>} {t==='xlsx'&&<XlsxViewer file={item.file}/>} {['hwp','hwpx'].includes(t)&&<HwpViewer file={item.file}/>} {t==='pptx'&&<PptxViewer file={item.file}/>}</div></div>}
export default function App(){const inputRef=useRef(null);const[items,setItems]=useState([]),[viewer,setViewer]=useState(null),[mergeName,setMergeName]=useState('모든문서뷰어_병합.pdf'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),[installPrompt,setInstallPrompt]=useState(null);React.useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[]);const mergeable=useMemo(()=>items.filter(x=>MERGEABLE.has(ext(x.file.name))),[items]);const readonlyCount=items.length-mergeable.length;
function addFiles(fileList){const all=Array.from(fileList||[]),next=all.filter(f=>SUPPORTED.includes(ext(f.name))).map(file=>({id:uid(),file}));if(!next.length){setStatus('추가할 수 있는 지원 파일이 없어요.');return}setItems(p=>[...p,...next]);const excluded=all.length-next.length;setStatus(excluded>0?`${next.length}개 파일을 추가했고, 지원하지 않는 ${excluded}개 파일은 제외했어요.`:`${next.length}개 파일을 기기 메모리에 추가했어요.`)}
function handleDragEnter(e){e.preventDefault();e.stopPropagation();setDragging(true)}
function handleDragOver(e){e.preventDefault();e.stopPropagation();if(e.dataTransfer)e.dataTransfer.dropEffect='copy';setDragging(true)}
function handleDragLeave(e){e.preventDefault();e.stopPropagation();if(e.currentTarget===e.target)setDragging(false)}
function handleDrop(e){e.preventDefault();e.stopPropagation();setDragging(false);if(e.dataTransfer?.files?.length)addFiles(e.dataTransfer.files)}
function move(index,delta){setItems(prev=>{const arr=[...prev],ni=index+delta;if(ni<0||ni>=arr.length)return arr;[arr[index],arr[ni]]=[arr[ni],arr[index]];return arr})}function remove(id){setItems(p=>p.filter(x=>x.id!==id))}
async function mergePdf(){if(!mergeable.length||busy)return;setBusy(true);setStatus('PDF를 만들고 있어요…');try{const out=await PDFDocument.create();for(const item of items){const t=ext(item.file.name);if(!MERGEABLE.has(t))continue;const bytes=await item.file.arrayBuffer();if(t==='pdf'){const src=await PDFDocument.load(bytes);const copied=await out.copyPages(src,src.getPageIndices());copied.forEach(p=>out.addPage(p))}else{const image=t==='png'?await out.embedPng(bytes):await out.embedJpg(bytes);const dims=image.scale(1);const page=out.addPage([dims.width,dims.height]);page.drawImage(image,{x:0,y:0,width:dims.width,height:dims.height})}}const bytes=await out.save();const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(mergeName||'모든문서뷰어_병합.pdf').replace(/\.pdf$/i,'')+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(`${out.getPageCount()}페이지 PDF를 만들었어요. 다운로드 폴더를 확인해 주세요.`)}catch(e){console.error(e);setStatus('PDF를 만들지 못했어요. 파일이 손상되지 않았는지 확인해 주세요.')}finally{setBusy(false)}}
async function installApp(){if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}if(viewer)return <Viewer item={viewer} onClose={()=>setViewer(null)}/>;
return <main className="app"><header className="hero"><div className="eyebrow">내 기기에서 바로 보기</div><h1>모든문서뷰어</h1><p>PDF, 이미지, 한글, 워드, 엑셀, 파워포인트 문서를 한곳에서 확인하고 PDF와 이미지를 하나로 합쳐 저장하세요.</p><div className="privacy-pill">파일은 서버로 전송하지 않고 브라우저 안에서 처리합니다.</div></header><section className={`card add-card drop-zone ${dragging?'dragging':''}`} onDragEnter={handleDragEnter} onDragOver={handleDragOver} onDragLeave={handleDragLeave} onDrop={handleDrop}><input ref={inputRef} type="file" multiple hidden accept=".pdf,.jpg,.jpeg,.png,.hwp,.hwpx,.docx,.xlsx,.pptx" onChange={e=>{addFiles(e.target.files);e.target.value=''}}/><div className="drop-copy"><div className="drop-icon">⇩</div><strong>{dragging?'여기에 놓으면 파일이 추가돼요':'파일을 여기로 끌어다 놓으세요'}</strong><span>PC에서는 드래그앤드롭, 휴대폰에서는 아래 버튼을 이용하세요.</span></div><button className="primary big" onClick={()=>inputRef.current?.click()}>파일 추가하기</button>{installPrompt&&<button className="secondary big" onClick={installApp}>홈 화면에 앱 설치</button>}<div className="formats">PDF, JPG, JPEG, PNG, HWP, HWPX, DOCX, XLSX, PPTX</div><div className="hint">HWP/HWPX, DOCX, XLSX, PPTX는 보기 전용이며 PDF 병합에는 넣지 않습니다.</div></section>{status&&<div className="status">{status}</div>}<section className="card"><div className="section-title"><h2>불러온 파일</h2><span>{items.length}개</span></div>{!items.length?<div className="empty">아직 불러온 파일이 없어요.</div>:<div className="file-list">{items.map((item,i)=>{const t=ext(item.file.name),order=mergeable.findIndex(x=>x.id===item.id)+1;return <div className="file-card" key={item.id}><div className="file-icon">{fileLabel(t)}</div><div className="file-info"><strong>{item.file.name}</strong><small>{fileLabel(t)} · {prettySize(item.file.size)} · 기기 파일</small><button className="link-btn" onClick={()=>setViewer(item)}>{MERGEABLE.has(t)?`PDF에 넣을 순서 ${order} · 눌러서 보기`:'보기 전용 · PDF 병합 제외 · 눌러서 보기'}</button></div><div className="file-actions"><button onClick={()=>move(i,-1)} disabled={i===0}>위로</button><button onClick={()=>move(i,1)} disabled={i===items.length-1}>아래로</button><button className="danger" onClick={()=>remove(item.id)}>삭제</button></div></div>})}</div>}</section><section className="card merge-card"><h2>하나의 PDF로 만들기</h2><p>PDF와 이미지를 위 목록의 순서대로 하나의 PDF로 만들어요.</p><div className="merge-stats"><span>병합할 파일 <b>{mergeable.length}개</b></span><span>보기 전용 문서 <b>{readonlyCount}개</b></span></div><label className="field-label">저장할 파일명</label><input className="text-input" value={mergeName} onChange={e=>setMergeName(e.target.value)}/><button className="primary big" disabled={!mergeable.length||busy} onClick={mergePdf}>{busy?'PDF 만드는 중…':'PDF 만들고 다운로드'}</button></section><footer className="footer"><a href="/guide.html">사용 가이드</a><a href="/privacy.html">개인정보처리방침</a><span>© 미니웍스</span></footer></main>}
